### ISSUE TITLE
Android kotlin - Request failed with status -3

### ISSUE THREAD

**Issue by jennaharris7** [Estimote/Android-Estimote-UWB-SDK#1]
com.estimote:uwb-sdk:1.0.0-rc5
I have the development kit, 3 beacons
All beacons set up in cloud with location and tags
Testing on Samsung Galaxy s24 Ultra

I'm seeing the same error on both my own app with the sdk implemented but also with the sample app out of the box.

Here are the logs when calling `uwbManager.startDeviceScanning(context)` :

```BLE-CONNECTION 		D onDeviceConnecting()
BluetoothAdapter            	D  getBleEnabledArray(): ON
BluetoothGatt               		D  connect() - device: XX:XX:XX:XX:F3:31, auto: false
BluetoothGatt               		D  registerApp()
BluetoothGatt               		D  registerApp() - UUID=c1b3bfb7-e319-4462-aa9d-76018c645def
BluetoothGatt               		D  onClientRegistered() - status=0 clientIf=15
BluetoothAdapter            	D  getBleEnabledArray(): ON
BluetoothGatt               		D  onClientConnectionState() - status=0 clientIf=13 device=XX:XX:XX:XX:F3:31
BluetoothGatt               		D  onClientConnectionState() - status=0 clientIf=15 device=XX:XX:XX:XX:F3:31
BluetoothGatt               		D  onClientConnectionState() - status=0 clientIf=14 device=XX:XX:XX:XX:F3:31
BLE-CONNECTION              	D  onDeviceConnected()
BLE-CONNECTION              	D  onDeviceConnected()
BLE-CONNECTION              	D  onDeviceConnected()
BluetoothGatt                   	D  discoverServices() - device: XX:XX:XX:XX:F3:31
BluetoothGatt               		D  discoverServices() - device: XX:XX:XX:XX:F3:31
BluetoothGatt              		D  discoverServices() - device: XX:XX:XX:XX:F3:31
BluetoothGatt               		D  onConnectionUpdated() - Device=XX:XX:XX:XX:F3:31 interval=6 latency=0 timeout=500 status=0
BluetoothGatt               		D  onConnectionUpdated() - Device=XX:XX:XX:XX:F3:31 interval=6 latency=0 timeout=500 status=0
BluetoothGatt               		D  onConnectionUpdated() - Device=XX:XX:XX:XX:F3:31 interval=6 latency=0 timeout=500 status=0
BluetoothGatt               		D  onSearchComplete() = Device=XX:XX:XX:XX:F3:31 Status=0
BluetoothGatt               		D  onSearchComplete() = Device=XX:XX:XX:XX:F3:31 Status=0
BluetoothGatt               		D  onSearchComplete() = Device=XX:XX:XX:XX:F3:31 Status=0
BluetoothGatt               		D  setCharacteristicNotification() - uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e enable: true
BluetoothGatt               		D  setCharacteristicNotification() - uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e enable: true
BluetoothGatt               		D  setCharacteristicNotification() - uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e enable: true
BLE-CONNECTION              D  onDeviceReady()
BLE-CONNECTION              D  onDeviceReady()
BLE-CONNECTION              D  onDeviceReady()
UwbMangerImpl               	I  Creating Gms Client session scope
UwbMangerImpl               	I  Creating Gms Client session scope
UwbMangerImpl               	I  Creating Gms Client session scope
BluetoothGatt               		D  onConnectionUpdated() - Device=XX:XX:XX:XX:F3:31 interval=24 latency=0 timeout=500 status=0
BluetoothGatt               		D  onConnectionUpdated() - Device=XX:XX:XX:XX:F3:31 interval=24 latency=0 timeout=500 status=0
BluetoothGatt               		D  onConnectionUpdated() - Device=XX:XX:XX:XX:F3:31 interval=24 latency=0 timeout=500 status=0
AndroidRuntime              	E  FATAL EXCEPTION: main

no.nordicsemi.android.ble.exception.RequestFailedException: Request failed with status -3
at no.nordicsemi.android.ble.ktx.RequestSuspendKt$suspendCancellable$2$2.onRequestFailed(RequestSuspend.kt:362)
at no.nordicsemi.android.ble.Request.lambda$notifyFail$2$no-nordicsemi-android-ble-Request(Request.java:1266)
at no.nordicsemi.android.ble.Request$$ExternalSyntheticLambda0.run(Unknown Source:6)
at no.nordicsemi.android.ble.Request$1.post(Request.java:172)
at no.nordicsemi.android.ble.Request.notifyFail(Request.java:1263)
at no.nordicsemi.android.ble.BleManagerHandler.nextRequest(BleManagerHandler.java:3406)```

This looks to be `FailCallback.REASON_NULL_ATTRIBUTE`

**Comment by nealmegh** [comment]
I am also having the same issue. Any Solution?

**Comment by HamzaAzeem97** [comment]
@nealmegh @jennaharris7 does your app also get crashed on samsung galaxy s24 ultra mobile?

**Comment by nealmegh** [comment]
> @nealmegh @jennaharris7 does your app also get crashed on samsung galaxy s24 ultra mobile?
@HamzaAzeem97 Yes. I am using google pixel 8 Pro and Galaxy s23 ultra. When there are multiple beacons, the app crashes.

**Comment by Danc2050** [comment]
@nealmegh @HamzaAzeem97 

How did you guys even get this running? I get a "Hello world" screen. I also noticed some code errors (https://github.com/Estimote/Android-Estimote-UWB-SDK/issues/2). I will pay you guys if you are freelancers to tell me how to get it working on my machine.

**Comment by HamzaAzeem97** [comment]
@Danc2050 we can do google meet

**Comment by Danc2050** [comment]
> @Danc2050 we can do google meet

connellyd2050@gmail.com

**Comment by HamzaAzeem97** [comment]
@Danc2050 I sent you google meet invite link
